### ISSUE TITLE
Build fails, somehow related to Browserify

### ISSUE THREAD

**Issue by pepelsbey** [sabertooth-io/demo-battery_service#2]
```
npm run demo

> demo-battery_service@1.0.0 demo demo-battery_service
> npm run build && npm start

> demo-battery_service@1.0.0 build demo-battery_service
> browserify -t [babelify] ./src/index.js -o ./src/build/bundle.js

sh: browserify: command not found
```

No browserify found. OK, `npm i -g browserify`:

```
npm run demo

> demo-battery_service@1.0.0 demo demo-battery_service
> npm run build && npm start

> demo-battery_service@1.0.0 build demo-battery_service
> browserify -t [babelify] ./src/index.js -o ./src/build/bundle.js

> demo-battery_service@1.0.0 start demo-battery_service
> node server.js

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Object.exports._errnoException (util.js:1036:11)
    at exports._exceptionWithHostPort (util.js:1059:20)
    at Server._listen2 (net.js:1252:14)
    at listen (net.js:1288:10)
    at Server.listen (net.js:1384:5)
    at EventEmitter.listen (demo-battery_service/node_modules/express/lib/application.js:617:24)
    at Object.<anonymous> (demo-battery_service/server.js:9:5)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
```

Any idea how to fix it? Thank you.

**Comment by pepelsbey** [comment]
Full `npm-debug.log`

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/pepelsbey/.nvm/versions/node/v6.6.0/bin/node',
1 verbose cli   '/Users/pepelsbey/.nvm/versions/node/v6.6.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'demo' ]
2 info using npm@3.10.3
3 info using node@v6.6.0
4 verbose run-script [ 'predemo', 'demo', 'postdemo' ]
5 info lifecycle demo-battery_service@1.0.0~predemo: demo-battery_service@1.0.0
6 silly lifecycle demo-battery_service@1.0.0~predemo: no script for predemo, continuing
7 info lifecycle demo-battery_service@1.0.0~demo: demo-battery_service@1.0.0
8 verbose lifecycle demo-battery_service@1.0.0~demo: unsafe-perm in lifecycle true
9 verbose lifecycle demo-battery_service@1.0.0~demo: PATH: /Users/pepelsbey/.nvm/versions/node/v6.6.0/lib/node_modules/npm/bin/node-gyp-bin:/Users/pepelsbey/Projects/Статьи/Я и ИоТ/demo-battery_service/node_modules/.bin:/Users/pepelsbey/.nvm/versions/node/v6.6.0/bin:/Users/pepelsbey/.nvm/versions/node/v6.6.0/bin:/usr/local/Cellar/ruby/2.3.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/sbin:/usr/local/m-cli
10 verbose lifecycle demo-battery_service@1.0.0~demo: CWD: demo-battery_service
11 silly lifecycle demo-battery_service@1.0.0~demo: Args: [ '-c', 'npm run build && npm start' ]
12 silly lifecycle demo-battery_service@1.0.0~demo: Returned: code: 1  signal: null
13 info lifecycle demo-battery_service@1.0.0~demo: Failed to exec demo script
14 verbose stack Error: demo-battery_service@1.0.0 demo: `npm run build && npm start`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/Users/pepelsbey/.nvm/versions/node/v6.6.0/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/Users/pepelsbey/.nvm/versions/node/v6.6.0/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid demo-battery_service@1.0.0
16 verbose cwd demo-battery_service
17 error Darwin 15.6.0
18 error argv "/Users/pepelsbey/.nvm/versions/node/v6.6.0/bin/node" "/Users/pepelsbey/.nvm/versions/node/v6.6.0/bin/npm" "run" "demo"
19 error node v6.6.0
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error demo-battery_service@1.0.0 demo: `npm run build && npm start`
22 error Exit status 1
23 error Failed at the demo-battery_service@1.0.0 demo script 'npm run build && npm start'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the demo-battery_service package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run build && npm start
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs demo-battery_service
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls demo-battery_service
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by pepelsbey** [comment]
The same problem applies to [demo-heart_rate_service](https://github.com/sabertooth-io/demo-heart_rate_service).

**Comment by apeltz** [comment]
@pepelsbey I've run into this issue before. It appears the Node server was not properly closed upon the crash related to the missing node module. So the error is basically saying "you can't start listening on a port that a server is already listening on". The thing to do is to stop the server listening, which will free the port to be opened successfully when you run the app. To do this: You should be able to manually kill the server from the command line with `Ctrl + z` or `Ctrl + c` ... or if those don't work this [SO response](http://stackoverflow.com/questions/4075287/node-express-eaddrinuse-address-already-in-use-kill-server) has some other ways to fix the issue. At the end of the day, if none of those work, restarting your computer would definitely kill the process as well.
